### ISSUE TITLE
Feature: User can search players via IGN.

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/final-project#1]
## ⚙️ Feature

> ##### User can look up players by IGN.

## 📐 Functionality

> ##### The user will type in an IGN into the Search bar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/32602914/144729299-e7f8c9b0-6e26-47c0-8aec-1026f371f67e.png)
![image](https://user-images.githubusercontent.com/32602914/144965530-e90e3cdc-0192-490f-beed-c933ab2ebdc6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to search the API for given IGN & return the puuid, then fetch their current Icon, Level, and Ranking if applicable.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to show the main page and search bar.
- [x] Update component to change the main screen when a search is completed.
- [ ] Create a component to show the searched user's Icon, Level, Ranking, and IGN.
- [x] Update component to change upon a new Search.

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
