### ISSUE TITLE
Feature: User can view Champion Mastery.

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their Top 3 most played Champions including their mastery rating.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user searches for an IGN (or is logged in) they can see the top 3 most played champions of theirs or the IGN searched.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/32602914/144964937-5400c614-8111-4ce4-ac7c-22fe066fca83.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to pull puuid of the IGN and search for Champion Mastery.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to Display top 3 Champions and their Mastery.
- [ ] Update component if new IGN is searched.

### 🧑‍⚕️ Clean Up

- [ ] Make sure display fits nice and has space for future features.
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
